
name: attendance_pro
description: Advanced Attendance Tracking App (Flutter + Firebase)
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # Firebase
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.2.1
  firebase_messaging: ^15.0.4
  firebase_storage: ^12.1.2
  google_sign_in: ^6.2.1

  # State management
  flutter_riverpod: ^2.5.1

  # Device features
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  local_auth: ^2.3.0
  camera: ^0.11.0+2
  image_picker: ^1.1.2
  mobile_scanner: ^6.0.2

  # Utils
  intl: ^0.19.0
  uuid: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
